<div class="span3 sidebar-wrapper">
	<ul class="nav nav-list">
		<li><a href="/" class="btn nav-button btn-large">Главная</a></li>
		<li><a href="production.php" class="btn nav-button btn-large">Продукция</a></li>
		<li><a href="price.php" class="btn nav-button btn-large">Прайс</a></li>
		<li><a href="techreq.php" class="btn nav-button btn-large">Тех. условия</a></li>
		<li><a href="contacts.php" class="btn nav-button btn-large">Контакты</a></li>
	</ul>
</div>