<div class="container">
	<h4>Издательский дом КНАУБ - рекламно-полиграфическая компания</h4>
	<br>
	<p>Адрес: 404121, г. Волжский, ул. Горького, 41 р <br>
	Часы работы: с 8:00 до 17:00. Сб, Вс - выходные <br>
	Телефон: 8-909-379-65-68 <br>
	e-mail: <a href="mailto:bloknot34@inbox.ru">bloknot34@inbox.ru</a>
	<br>
	Адрес группы ВКонтакте: <a href="http://vk.com/bloknot_34">vk.com/bloknot_34</a>
	</p>

	<div id="map">
	<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=XvpKYtqWtmzcxIL2WXEoTP7aE8rGBGXu&width=600&height=450"></script>
	</div>
</div>

