<div class="container">
	<h4 class="h4">Издательский дом &laquo;Кнауб&raquo;<br /><small>рекламно-полиграфическая компания</small></h4>
	<br>
	<p>
        <dl class="dl-horizontal">                        
            <dt>Адрес:</dt>            
            <dd>404121, г.&nbsp;Волжский, ул.&nbsp;Горького, 41&thinsp;р</dd>            
            <dt>Телефон:</dt>
            <dd>8 909-379-65-68</dd>                        
            <dt>E-mail:</dt>            
            <dd><a href="mailto:bloknot34@inbox.ru">bloknot34@inbox.ru</a></dd>
            <dt>ВКонтакте:</dt>
            <dd><a href="http://vk.com/bloknot_34">vk.com/bloknot_34</a></dd>
        </dl>         
	</p>

	<div id="map">
	<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=XvpKYtqWtmzcxIL2WXEoTP7aE8rGBGXu&width=600&height=450"></script>
	</div>
</div>

