<div class="container">
		<div class="row">
		<div class="col-md-6">
			<h4>Предлагаем вам</h4>
			<ul class="marker-checkmark">
				
				<li><span class="bigger">Производство банерной продукции, монтаж и&nbsp;размещение</span></li>
				<li><span class="bigger">Интерьерная и&nbsp;авто пленка, фотообои (плоттерная резка)</span></li>
				<li><span class="bigger">Интерьерная печать на&nbsp;фотобумаге, пленке</span></li>
				
				<li>Печать визиток, листовок, буклетов и&nbsp;т.&nbsp;д.</li>
				<li>Печать открыток, пригласительных</li>
				<li>Услуги дизайнера, разработка логотипа и&nbsp;фирменного стиля</li>	
				<li>Изготовление календарей любой сложности, блокнотов, каталогов</li>
				<li>Переплет, магниты, флажки, брелки</li>
				<li>Фольгирование (золото, серебро и&nbsp;т.&nbsp;д.) и&nbsp;ламинирование</li>
				<li>Печать производственных и&nbsp;служебных журналов, бланков, дипломных работ</li>
			 	<li>Печать чертежей</li>
			</ul>		

		</div>
		<div class="col-md-3">
			<h4>Наши услуги</h4>
			<ul class="marker-checkmark">
				<li>Дизайн</li>
				<li>Полиграфия</li>
				<li>Сувенирная продукция</li>
				<li>Наружная реклама</li>
				<li>Интерьерная печать</li>
				<li>Оперативное изготовление</li>
				<li>Качество</li>
				<li>Бесплатная доставка</li>
			</ul>
			
		</div>
		<div class="col-md-3">
			<img src="img/digital.png" alt="Типографское оборудование">
			</a>

		</div>
	</div>
</div>


<div class="stripe">
    <div class="container">
        <div class="row">
            <div class="col-md-12 vtop">
                <table id="main-links">                        
                    <col>
                    <col width="200">
                    <tr>
                        <td><span class="marker-barcode"></span>&nbsp;&nbsp;</td>
                        <td><a href="?c=2"><button type="button" class="btn btn-primary btn-lg">Прайс-лист</button></a></td>
                        <td class="vbot">&nbsp;&nbsp;&nbsp;<span class="marker-numbered-list"></span>&nbsp;&nbsp;</td>
                        <td class="vbot"><a href="?c=3"><button type="button" class="btn btn-default">Технические условия</button></a></td>
                    </tr>
                </table>            
            </div>
		</div>
	</div>
</div>
