<div class="container">
		<div class="row">
            <div class="col-md-5">	
                <img src="/img/digital.png" alt="Типографское оборудование" id="equipment" width="100%" />
                <ul class="marker-checkmark" id="offers">
                    <li>Дизайн</li>
                    <li>Полиграфия</li>
                    <li>Сувенирная продукция</li>
                    <li>Наружная реклама</li>
                    <li>Интерьерная печать</li>
                    <li>Оперативное изготовление</li>
                    <li>Качество</li>
                </ul>
            </div>	
            <div class="col-md-7 rightside">
                <div id="marquee-basement">
                    <marquee>Собираем бегущие строки и цветные экраны! Продажа светодиодных экранов в Волжском и Волгограде! Аренда рекламного места &mdash; от 130 руб. в сутки!</marquee>
                </div>
                <p>Замена всей статичной рекламы (баннеры, световые короба, объёмные буквы) на светодиодные медиавывески. Это красиво, это современно, это информативно, это интересно!</p>
                <div class="row" id="lightboxes">
                    <div class="col-md-4">
                        <a href="/img/main/lightbox_01L.jpg" data-lightbox="lightboxes"><img src="/img/main/lightbox_01.jpg" width="100%" /></a>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/lightbox_02L.jpg" data-lightbox="lightboxes"><img src="/img/main/lightbox_02.jpg" width="100%" /></a>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/lightbox_03L.jpg" data-lightbox="lightboxes"><img src="/img/main/lightbox_03.jpg" width="100%" /></a>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/lightbox_04L.jpg" data-lightbox="lightboxes"><img src="/img/main/lightbox_04.jpg" width="100%" /></a>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/lightbox_05L.jpg" data-lightbox="lightboxes"><img src="/img/main/lightbox_05.jpg" width="100%" /></a>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/lightbox_06L.jpg" data-lightbox="lightboxes"><img src="/img/main/lightbox_06.jpg" width="100%" /></a>
                    </div>
                </div>

                <h4>Светодиодные вывески<br /><span class="f12">Кликните для просмотра демонстрации</span></h4>
                <div class="row" id="diodes">
                    <div class="col-md-4">
                        <a href="/img/main/001.gif" data-lightbox="photo"><img title="Светодиодная вывеска для аптеки" alt="Светодиодная вывеска для аптеки" src="/img/main/001.jpg" width="100%" /></a>
                        <h6>Для аптек</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/002.gif" data-lightbox="photo"><img title="Светодиодная вывеска для кафе" alt="Светодиодная вывеска для кафе" src="/img/main/002.jpg" width="100%" /></a>
                        <h6>Для кафе</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/003.gif" data-lightbox="photo"><img title="Светодиодная вывеска для салона сотовой связи" alt="Светодиодная вывеска для салона сотовой связи" src="/img/main/003.jpg" width="100%" /></a>
                        <h6>Для салона связи</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/004.gif" data-lightbox="photo"><img title="Светодиодная вывеска для магазина строительных материалов" alt="Светодиодная вывеска для магазина строительных материалов" src="/img/main/004.jpg" width="100%" /></a>
                        <h6>Для магазина строительных материалов</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/005.gif" data-lightbox="photo"><img title="Светодиодная вывеска для стоматологии" alt="Светодиодная вывеска для стоматологии" src="/img/main/005.jpg" width="100%" /></a>
                        <h6>Для стоматологии</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/006.gif" data-lightbox="photo"><img title="Светодиодная вывеска для магазина для взрослых" alt="Светодиодная вывеска для магазина для взрослых" src="/img/main/006.jpg" width="100%" /></a>
                        <h6>Для магазина для взрослых</h6>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-4">
                        <a href="/img/main/007.gif" data-lightbox="photo"><img title="Светодиодная вывеска для цветочного магазина" alt="Светодиодная вывеска для цветочного магазина" src="/img/main/007.jpg" width="100%" /></a>
                        <h6>Для цветочного магазина</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/008.gif" data-lightbox="photo"><img title="Светодиодная вывеска для магазина женской обуви" alt="Светодиодная вывеска для магазина женской обуви" src="/img/main/008.jpg" width="100%" /></a>
                        <h6>Для магазина женской обуви</h6>
                    </div>
                    <div class="col-md-4">
                        <a href="/img/main/009.gif" data-lightbox="photo"><img title="Светодиодная вывеска для круглосуточного продуктового магазина" alt="Светодиодная вывеска для круглосуточного продуктового магазина" src="/img/main/009.jpg" width="100%" /></a>
                        <h6>Для круглосуточного продуктового магазина</h6>
                    </div>
                </div>
            </div>
            
        </div>
</div>

<div class="stripe">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <? /*
                        <div class="alert alert-success">Акция: услуги дизайнера, разработка логотипа и&nbsp;фирменного стиля&nbsp;&mdash; бесплатно.</div>  
                        */ ?>
                        <img src="/img/banner.jpg" alt="Акция" />
                    </div>
                    <div class="col-md-6">
                        <? /*
                        <div id="ad-delivery">Мы также осуществим <strong>бесплатную доставку</strong> заказанной вами полиграфии!</div>
                        */ ?>
                        <img src="/img/banner2.jpg" alt="Доставка" />
                    </div>
                </div>
                <div class="row">
                    <br /><br />
                    <div class="centered">Надеемся на взаимовыгодное сотрудничество</div>
                </div>
            </div>
        </div>