<div class="container">
		<div class="row">
            <div class="col-md-6">		
                <ul class="marker-checkmark">
                    <li>Дизайн</li>
                    <li>Полиграфия</li>
                    <li>Сувенирная продукция</li>
                    <li>Наружная реклама</li>
                    <li>Интерьерная печать</li>
                    <li>Оперативное изготовление</li>
                    <li>Качество</li>
                    <li>Бесплатная доставка</li>
                </ul>
            </div>	
            <div class="col-md-6">
                <img src="/img/digital.png" alt="Типографское оборудование" id="equipment" />
            </div>
        </div>
</div>

<div class="stripe">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="alert alert-success">Акция: услуги дизайнера, разработка логотипа и&nbsp;фирменного стиля&nbsp;&mdash; бесплатно.</div>  
                    </div>
                    <div class="col-md-6">
                        <div class="alert alert-info">Мы также осуществим <strong>бесплатную доставку</strong> заказанной вами полиграфии!</div>
                    </div>
                </div>
                <div class="row">
                    <div class="centered">Надеемся на взаимовыгодное сотрудничество</div>
                </div>
            </div>
        </div>